### ISSUE TITLE
Running ajaxSetup multiple times clobbers whatever the previous settings were.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments-ui#186]
* If we're going to move to a fetch polyfill then this is moot. Otherwise we should look at fixing this.

**Comment by kumar303** [comment]
It would probably be easier to port to the fetch polyfill if we have test coverage on all Ajax code: https://github.com/mozilla/payments-ui/issues/187

Also, a quick and easy way to prevent settings clobbering would be to make a wrapper function around the jquery ``$.ajax()`` call so that it passed the CSRF header repeatedly instead of configuring it once in settings.

**Comment by muffinresearch** [comment]
This is fixed now with the api fetch wrapper.

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/payments-service/pull/125

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/payments-ui/pull/266
