### ISSUE TITLE
Missing mozilla branding

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#285]
Most (if not all) Mozilla properties use tabzilla to have mozilla in the top right hand corner. The spiffy new management interface doesn't have anything for that.

It also doesn't have a footer that contains required links like: privacy policy and terms of use.

Should we have those sorts of features accessible somewhere.

**Comment by brampitoyo** [comment]
Firefox accounts has a small Mozilla logo (not inside a tab shape) in the top right hand corner. Perhaps we can follow this convention?

![fxa-home-page](https://cloud.githubusercontent.com/assets/51007/9128089/c9fd2ae6-3d17-11e5-9ab2-b13c9aa88356.PNG)

Notice that it also has links to ToS and Privacy Notice on the bottom of the div element. Unfortunately, we can’t follow their convention since our layout is different.

So I suggest having ToS and Privacy be located under “My account”, just below “Delete account”, as plain text links. What do you think?

**Comment by tofumatt** [comment]
For privacy and ToS, that makes sense to me, assuming it's okay (legally speaking) not to have those links at the bottom of every page.



Does the tabzilla tab look out of place? It would be nice to be consistent with other Mozilla sites and get their content for free. I like the way that grey Mozilla logo looks but it's just branding and isn't very functional (i.e. it doesn't look/feel "clickable" like tabzilla).



- tofumatt

**Comment by muffinresearch** [comment]
+1 to Tabzilla. Tabzilla is now static so we could use it. (Thus far everything UI related is static). 

https://github.com/mozilla/tabzilla/

**Comment by muffinresearch** [comment]
Ok I did  a quick branch to test tabzilla. This is what it could look like:

The static version is just white image (with the wordmark transparent) so I needed to make the background grey (I used the same grey as fxa) or you can't see the tab at all.

<img width="718" alt="mozilla_firefox_and_terminal_ _ssh_ _80x40" src="https://cloud.githubusercontent.com/assets/1514/9132947/353e2900-3cef-11e5-8983-93c1120982b2.png">

What do you think otherwise we can go the same route as fxa and keep the white background. Or alternatively we can colourize the tab (assuming that's not breaking some unwritten tabzilla rule).

**Comment by tofumatt** [comment]
I dig the grey background; nice contrast between the buttons and the background that way. And I'd rather not mess with the tabzilla colours.




It feels more like the Firefox browser preferences, which I like and don't think will confuse anyone into thinking they're actually in about:preferences.




+1 from me. 👍



—

**Comment by andymckay-limited-access** [comment]
I'll file a bug to add in terms of use and privacy policy when we get them from legal.
